trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: Default
  steps:   
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'BasicAuth-artifactory'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "maven-remote-smart",
              "target": "/download"
            }
          ]
        }
      failNoOp: true
