trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: nitaym
  steps:   
  - task: JfrogCli@1
    inputs:
      command: 'jfrog rt s maven-remote-smart --build "my-build" --transitive'