trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: nitaym
  steps:   
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'basic-nitaym'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
            "aql": {
                "items.find": {
                  "repo": "maven-remote-smart"
                  }
            },
            "target": "Downloads2/"
            }
          ]
        }
      collectBuildInfo: true
      failNoOp: true
