trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: nitaym
  steps:   
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'basic-nitaym'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "maven-remote-smart/telemetry-core-0.12.0.jar"
              "build": "my-build,1.0.0",
              "target": "Downloads2/"
            }
          ]
        }
      collectBuildInfo: true
      buildName: 'my-build'
      buildNumber: '1.0.0'
      failNoOp: true
