trigger:
- master


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    name: nitaym
  steps:   
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'basic-nitaym'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "maven-remote-smart/*",
              "target": "/download"
            }
          ]
        }
      failNoOp: true

  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'basic-nitaym'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "maven-remote-smart",
              "target": "/Downloads"
            }
          ]
        }
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      failNoOp: true
